spring.application.name=blogly
spring.profiles.active=local

# application-local.properties
jwt.secret=${jwt.secret}
jwt.expiration=${jwt.expiration}

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}

frontend.url=${FRONTEND_URL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true